#============================================================================================================================|
#    _____                          .__        _____   .__         .__                 
#   /     \    ____ _______ ______  |  |__    /     \  |__|  ____  |__|  ____    ____  
#  /  \ /  \  /  _ \\_  __ \\____ \ |  |  \  /  \ /  \ |  | /    \ |  | /    \  / ___\ 
# /    Y    \(  <_> )|  | \/|  |_> >|   Y  \/    Y    \|  ||   |  \|  ||   |  \/ /_/  >
# \____|__  / \____/ |__|   |   __/ |___|  /\____|__  /|__||___|  /|__||___|  /\___  / 
#         \/                |__|         \/         \/          \/          \//_____/  
#
#============================================================================================================================|
#
# Plugin Version: 1.6.2
# Spigot Link: https://www.spigotmc.org/resources/morphmining.53827/
# Author's Discord: Morphie#6969
# 
# If you have issues or questions feel free to message me on spigot OR discord.
# Please do keep in mind however that I will respond when I can! <3
#
#============================================================================================================================|

Settings:
  # Data value ranges from 0 - 15.
  MainGlassColor: 11
  # Whether players are given a DataLog on first join!
  GiveBookOnFirstJoin: true
  # Change the item type of the artifact.
  ArtifactItem: "GOLD_NUGGET"
  #Change the item type of the hellstone artifact.
  HellstoneItem: "FIREWORK_STAR"
  # Change the drop chance of all Artifact types.
  # This value can only be between 0 - 100. EX. Common: 10 means 10% chance to receive a common artifact from coal ore.
  # These values might seem low but do remember how much more coal ore there is in a world compared to diamond/emerald.
  ArtifactChances:
    Common: 10
    Rare: 13
    Legendary: 17
    Mythic: 20
    HellStone: 15

#============================================================================================================================|

# Change the price of artifacts here!
ArtifactPrice:
  Common: 50.00
  Rare: 250.00
  Legendary: 750.00
  Mythic: 2500.00
  HellStone: 1000.00
  
#============================================================================================================================|
  
# Change the gem chances of the ore grinder. (0 - 100)
OreGrinder:
  CoalGemChance: 5
  IronGemChance: 10
  GoldGemChance: 10
  RedstoneGemChance: 15
  LapisGemChance: 20
  DiamondGemChance: 25
  EmeraldGemChance: 30
  
#============================================================================================================================|

# Here you can change things about the pouch system. Pouches are a craftable item that allows the user to store artifacts.
# Pouches have levels that unlock more capacity space at the cost of gems and your servers currency.
Pouches:
  AutoSell:
    GemCost: 50
  Common:
    StartCapacity: 100
    UpgradedCapacity: 200
    GemCost: 100
    CurrencyCost: 1500.00
  Rare:
    StartCapacity: 75
    UpgradedCapacity: 150
    GemCost: 150
    CurrencyCost: 3000.00
  Legendary:
    StartCapacity: 50
    UpgradedCapacity: 100
    GemCost: 250
    CurrencyCost: 5000.00
  Mythic:
    StartCapacity: 50
    UpgradedCapacity: 100
    GemCost: 350
    CurrencyCost: 7000.00
    
#============================================================================================================================|

# Here you can change things about the trashcan system. Trashcans are a craftable item that allows the user to delete items
# that are placed into it. Trashcans have slots that users can unlock to nullify multiple block types at once.
# Slot 1 at default is unlocked and that is why it is not listed below.
Trashcan:
  Slot2:
    GemCost: 250
    CurrencyCost: 5000.00
  Slot3:
    GemCost: 350
    CurrencyCost: 7000.00
  Slot4:
    GemCost: 700
    CurrencyCost: 10000.00
    
#============================================================================================================================|
    
# Below you can change the custom recipes that are implemented in the plugin.
# "Amount:" How many of the item that is given to the player when crafting. (I.E 1 trashcan)
# "Line1,2,3:" This stands for the crafting grid lines. This is the order of the recipe items in a crafting grid.
# "Ingredients:" This is how you set the items that the recipe needs. The "Key" is what is used in the crafting grid above.
# If you run into issues feel free to contact me on discord or spigot. (Contact details at the top of the config.)
Recipes:
  Datalog:
    Enabled: true
    Amount: 1
    Line1: "###"
    Line2: "#$#"
    Line3: "###"
    Ingredients:
      0:
        Key: "#"
        Material: "LEATHER"
      1:
        Key: "$"
        Material: "BOOK"
  Pouch:
    Enabled: true
    Amount: 1
    Line1: "#$#"
    Line2: "#%#"
    Line3: "###"
    Ingredients:
      0:
        Key: "#"
        Material: "LEATHER"
      1:
        Key: "$"
        Material: "ENDER_EYE"
      2:
        Key: "%"
        Material: "ENDER_CHEST"
  Trashcan:
    Enabled: true
    Amount: 1
    Line1: "#$#"
    Line2: "#%#"
    Line3: "###"
    Ingredients:
      0:
        Key: "#"
        Material: "IRON_INGOT"
      1:
        Key: "$"
        Material: "CAULDRON"
      2:
        Key: "%"
        Material: "LAVA_BUCKET"
      
#============================================================================================================================|      

# Got a neat idea for an artifact? Create your own here!
# Keep in mind the description will only set 1 line of the lore.
# Color codes supported!
Artifacts:
  Common:
    0:
      Name: "&9&lHelix Fossil"
      Description: "&b➛ &7&oOAK: Ash! This isn't the time to use that!"
  Rare:
    0:
      Name: "&9&lRelic of a Super Sayian"
      Description: "&b➛ &7&oKio what!?"
  Legendary:
    0:
      Name: "&9&lEcho's Fortune"
      Description: "&b➛ &7&oCan you hear me now?"
  Mythic:
    0:
      Name: "&9&lTorments Serenity"
      Description: "&b➛ &7&oAre you crying?"
  HellStone:
    0:
      Name: "&9&lHell Stone"
      Description: "&b➛ &7&oIs something burning?"
      
#============================================================================================================================|